service: dva-c02-course

provider:
  name: aws
  region: us-east-1
  stage: ${opt:stage, 'prod'}
  
custom:
  domains:
    prod: dva.sstechnologies-cloud.com
  
  buckets:
    prod: dva-c02-course-prod-${aws:accountId}

resources:
  Resources:
    # S3 Bucket para hospedagem
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: dva-c02-course-prod-${aws:accountId}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
    
    # Bucket Policy para acesso público
    WebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref WebsiteBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action: s3:GetObject
              Resource: !Sub '${WebsiteBucket}/*'
    
    # CloudFront Distribution
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: !GetAtt WebsiteBucket.RegionalDomainName
              Id: S3Origin
              S3OriginConfig:
                OriginAccessIdentity: ''
          Enabled: true
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            Compress: true
            DefaultTTL: 86400
            MaxTTL: 31536000
          Aliases:
            - dva.sstechnologies-cloud.com
          ViewerCertificate:
            AcmCertificateArn: 
              Ref: SSLCertificate
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
    
    # SSL Certificate
    SSLCertificate:
      Type: AWS::CertificateManager::Certificate
      Properties:
        DomainName: dva.sstechnologies-cloud.com
        ValidationMethod: DNS
        DomainValidationOptions:
          - DomainName: dva.sstechnologies-cloud.com
            HostedZoneId: Z07937031ROGP6XAEMPWJ
    
    # Route53 Record
    DNSRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: Z07937031ROGP6XAEMPWJ
        Name: dva.sstechnologies-cloud.com
        Type: A
        AliasTarget:
          DNSName: !GetAtt CloudFrontDistribution.DomainName
          HostedZoneId: Z2FDTNDATAQYW2 # CloudFront HostedZoneId

  Outputs:
    WebsiteURL:
      Description: Website URL
      Value: https://dva.sstechnologies-cloud.com
    
    CloudFrontDistributionId:
      Description: CloudFront Distribution ID
      Value: !Ref CloudFrontDistribution
    
    S3BucketName:
      Description: S3 Bucket Name
      Value: !Ref WebsiteBucket

# Plugins removidos - deploy manual via CLI

# Site estático - sem packaging necessário